### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by badchulo** [gegehprast/f1-telemetry#1]
No idea what is happening.
![image](https://user-images.githubusercontent.com/19668212/188282816-a762b747-09c3-4035-9dd9-2bd199153211.png)

Edit: After change server project port to 3001 web is working
![image](https://user-images.githubusercontent.com/19668212/188283156-ca5e8b36-1c2f-43d7-8368-af81950e0f4a.png)
but API is always returning empty array.

UDP activated on F1 22 (Actually working with Sim dashboard android app)

**Comment by gegehprast** [comment]
Hello! 

> but API is always returning empty array.

Maybe your database is still empty? Have you tried some laps in the game?
